### ISSUE TITLE
How can I visualize the 3D boxes?

### ISSUE THREAD

**Issue by FranciscoGomez90** [abhi1kumar/DEVIANT#16] opened 2023-10-03 08:53 UTC
Hi all!
I managed to run the experiments on kitti, no issues.
But I would like to run the model and visualize the output of a single image. Is there a script to do that?
thank you!

**Comment by abhi1kumar** [comment] 2023-10-03 14:21
Hi @FranciscoGomez90 
Thank you for your interest in DEVIANT. The issue is duplicate of #11 

The visualization code is in the qualitative plots in the README at this [link](https://github.com/abhi1kumar/DEVIANT#qualitative-plotsvisualization). The code is 
```bash
python plot/plot_qualitative_output.py --dataset kitti --folder output/run_221/results_test/data
python plot/plot_qualitative_output.py --dataset waymo --folder output/run_1051/results_test/data
```

PS - In case you find our repository useful, please consider supporting by starring it.

**Closed as completed** 2023-10-07 19:27 UTC
Labels: duplicate
